name: farmdidi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  build_runner: ^2.1.10
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  
  sqflite:
  dio:
  path_provider: 2.0.11 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.5
  favorite_button: ^0.0.4
  link_text: ^0.2.0
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

